### ISSUE TITLE
Command supports and developing work informations

### ISSUE THREAD

**Issue by vincenzopalazzo** [AraguaneyBits/bitcoinrpc4java#21]
Hello, I want to ask if it is possible to support the `gettxout` command, or if a PR is welcome.

I'm working on a c-lightning [btcli4j](https://github.com/clightning4j/btcli4j) plugin and I need a bitcoin RPC library because I don't want to write another one (there are a lot around github). However, this library is a unique library updated and I want to know if you want to continue the development of it.

Thanks.

Vincent.

**Comment by jestevez** [comment]
Hi of course! this library is open sources and you can help improve it

**Comment by vincenzopalazzo** [comment]
Hello, I decide to develop a more general solution https://github.com/clightning4j/lite-bitcoin-rpc because I need to support also Litecoin and Elements blockchan.

Thanks for your time.
